### ISSUE TITLE
dependency issue (or is it?)

### ISSUE THREAD

**Issue by roovo** [ericgj/elm-csv-decode#1]
Hiya

firstly -> mega-thanks for releasing this - brilliant - really appreciated

...sooo i have just tried to replace the code I had dropped into my app from your original pull request and I've hit a dependency issue.  To be honest the error message isn't particularly clear (surprisingly for elm) and it's quite possible it has nothing to do with your package at all.

To reproduce:

- start a new elm project with elm make
- add a main with a basic hello world
- elm package install ericgj/elm-csv-decode
- elm package install evancz/url-parser

and it refuses to compile with an

![screen shot 2017-06-28 at 20 05 57](https://user-images.githubusercontent.com/5251/27655433-45c26254-5c3d-11e7-8cdc-8de2f57a77d4.png)

error. I can get it to complain about either elm-csv-decode or (as in the screenshot) url-parser depending on the order of adding packages.  If I add them one at a time and check with elm reactor before adding the second it always points the finger of accusation at the second one.

Just wondering if you have any ideas?  Or is this something to ask on elm-discuss (or slack or somewhere)

Cheers and big thanks again

roovo

**Comment by ericgj** [comment]
Ah, well if you try those steps in Ellie, you get a much more informative message.  At least, I'm assuming it's related to the same problem.  https://ellie-app.com/3BNqmhxbf4Qa1/0

> The infix declarations for () must be removed.
The precedence and associativity of a particular operator can only be set in one
place in a code base, and () has already been set somewhere else.

I think something related to this came up on the mailing list awhile back, I will see what I can find. I might need to change `</>` to something else  :'(   unfortunately `<,>`  doesn't compile....

**Comment by roovo** [comment]
Ah - yes - now I remember deleting that line when I copied it over... good shout.  I have just confirmed that this is the issue that I am seeing as if I comment out that line in my elm-stuff folder, delete the build-artifacts and re-run the reactor it builds and runs fine.

I know it's not much help to you for now, but it feels like a bit of a limitation (assuming I understand it properly) that you can't have 2 libraries using the same infix operator if they both want to set a non-default precedence.

...also, that error message is totally misleading! (again not your problem)

Cheers

**Comment by ericgj** [comment]
Reading over [Evan's negative thoughts on custom infix operators](http://package.elm-lang.org/help/design-guidelines#avoid-infix-operators) again, and given the 'global clash', I thought better to replace it with `|> andMap` .  See PR #2 . What do you think?  

Unfortunately it means extra parentheses, but on the positive side it looks more elm-ish with the `|>` pipeline. 

`andMap` is kind of an unofficial Elm name for this (AKA `ap` or `apply`), for instance see http://package.elm-lang.org/packages/krisajenkins/remotedata/4.3.0/RemoteData#andMap


EDIT:

I could also move the current `</>` to an `Csv.Decode.Infix` module, and just not set the precedence (which would mean however you'd have to set it yourself if you don't have `url-parser` or something else that already sets the precedence... looks like this is what RemoteData does. Kind of a mess).

**Comment by roovo** [comment]
Looks great to me - I'm plenty happy with the andMap style (even with the brackets).

Thanks doode

**Comment by ericgj** [comment]
done & released, thanks for the feedback!

**Comment by roovo** [comment]
brill - thanks - just tried it in my app and it's working a treat - most excellent - you're a ⭐️
