### ISSUE TITLE
0.19

### ISSUE THREAD

**Issue by woylie** [ericgj/elm-csv-decode#4]
I noticed the current master already includes changes for Elm 0.19, but the package hasn't been released yet on package.elm-lang.org. Are you planning to do so? Is there something left to do?

**Comment by ericgj** [comment]
Tried releasing it today but having a some difficulty with the 0.19 publish, hopefully just temporary.

**Comment by ericgj** [comment]
OK, it's released now  :fireworks:

**Comment by woylie** [comment]
Thanks!
